pylint fstrings and more
Miksus/rocketry pull request #127
Opened 2022-10-12 02:09 UTC by marksmayo

Some more tidy-ups with f-strings, uneeded vars, simplified additions and encodings.

2022-10-15 19:03 UTC, Miksus requested changes
In ``versioneer.py`` there is a minor thing that functionally differs from previous (a verbose print statement). This is very minor however.

2022-10-15 19:03 UTC, Miksus commented on rocketry/_version.py
> +            rendered += f".post{pieces['distance']}"
This produces the same (verified manually).

2022-10-15 19:03 UTC, Miksus commented on rocketry/_version.py
> +        rendered = f"0.post{pieces['distance']}"
This produces the same (verified manually).

2022-10-15 19:03 UTC, Miksus commented on rocketry/_version.py
> +        raise ValueError(f"unknown style '{style}'")
This produces the same (verified manually).

2022-10-15 19:12 UTC, Miksus approved these changes

2022-10-15 19:14 UTC, Miksus commented
Thanks again for the contribution! By the way, how are you using Pylint? I'm thinking of adding some linters (ie. using Flake8) to the CI to keep the code tidy in the future as well.

2022-10-15 19:14 UTC, merged

2022-10-20 03:53 UTC, marksmayo commented
I do it in two ways - on the command line (pylint_runner is a handy wrapper for it, and with -d options to hide ones I'm not trying to fix), and in VSCode where you edit the user settings.json file and hide the ones you don't want to see as well.

2022-10-20 03:53 UTC, marksmayo commented
You can add it as a Github action, and just -d the ones that currently exist as issues, thus preventing any new ones from being added at least?