More pylint fixes
Miksus/rocketry pull request #133
Opened 2022-10-20 21:16 UTC by marksmayo

Including some newly introduced ones when I rebased

2022-11-01 22:14 UTC, Miksus commented
Thanks! I'll try to check and merge before the end of the week. Sorry for the delay.

2022-11-15 19:33 UTC, Miksus requested changes
Just some (perhaps opinionated) suggestions to leave the "..." in some code snippets in the documentation to indicate a placeholder and there should be more code in practice.

For example:
```python
def do_things():
    "This does things"
    ...
```
Vs:
```python
def do_things():
    "This does things"
```

2022-11-15 19:33 UTC, Miksus commented on docs/code/conds/api/cron_kwargs.py
> +
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/snippets/custom_condition.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/demos/intermediate.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/demos/intermediate.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/demos/intermediate.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/demos/intermediate.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/demos/intermediate.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/demos/advanced.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/demos/advanced.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/demos/advanced.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/demo.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/demo.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/demo.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/conds/api/crontime_kwargs.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/conds/api/crontime_kwargs.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/conds/api/cron_kwargs.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:33 UTC, Miksus commented on docs/code/conds/api/cron.py
> -    ...
I think these could be excluded (the three dots indicate just a placeholder here to show the functions should not be this short).

2022-11-15 19:35 UTC, Miksus commented
Sorry it took almost a month to review (had a bad week, a busy week and a small side project). I think all of those changes are appropriate but I think some of those placehoder ``...`` could be left in the snippets in the docs.

2022-11-16 00:02 UTC, marksmayo reviewed
Think I've made them all

2022-11-16 00:02 UTC, marksmayo commented
Still says changes requested but I think I've resolved all? Just pulling in latest from your repo to see if I've missed any new ones

2022-11-20 10:49 UTC, Miksus approved these changes

2022-11-20 10:50 UTC, Miksus commented
Yep, looks good. Thanks again for the fixes and sorry for the immense delay. I now booked an hour every week to go through PRs and issues so hopefully, there won't be the same delay anymore.

2022-11-20 10:50 UTC, merged

2022-11-20 21:09 UTC, marksmayo commented
All good. I'm still learning so in no hurry.